export const SET_VIEWPORT = 'SET_VIEWPORT';
export const CHECK_BREAKPOINT = 'CHECK_BREAKPOINT';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const SET_WIDTH = 'SET_WIDTH';

export const SET_COUNTRY = 'SET_COUNTRY';
export const SET_COMPANY = 'SET_COMPANY';
export const SET_COMPANY_STRUCTURE = 'SET_COMPANY_STRUCTURE';
export const SET_OWNERSHIP_THRESHOLD = 'SET_OWNERSHIP_THRESHOLD';
export const SET_MARKETS = 'SET_MARKETS';
export const SET_COMPANY_CONTACT = 'SET_COMPANY_CONTACT';
export const SET_COMPLETION = 'SET_COMPLETION';
export const SET_ERRORS = 'SET_ERRORS';
export const EDIT_FIELD = 'EDIT_FIELD';
export const RESET_SCREENING = 'RESET_SCREENING';

export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_ERRORS = 'USER_SIGNIN_ERRORS';
export const USER_SIGNOUT = 'USER_SIGNOUT'
export const EDIT_USER = 'EDIT_USER';

export const SET_MODAL = 'SET_MODAL';
export const CLEAR_MODAL = 'CLEAR_MODAL';

export const SET_SIDE_TRAY = 'SET_SIDE_TRAY';
export const CLEAR_SIDE_TRAY = 'CLEAR_SIDE_TRAY';
