name: CI - Functions

on:
  push:
    branches:
      - master
    paths:
      - app/functions/**

jobs:
  build:
    name: Deploy functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: yarn add firebase-tools
      - name: Set functions secrets
        working-directory: ./app
        run: ./node_modules/.bin/firebase functions:config:set due_dill_api.key=${DUE_DILL_API_KEY} companies_house_api.key=${COMPANIES_HOUSE_API_KEY} companies_house_api.id="Companies house" --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY}}
          DUE_DILL_API_KEY: ${{ secrets.DUE_DILL_API_KEY}}
      - name: Install function dependencies
        working-directory: ./app/functions
        run: npm install 
      - name: Deploy functions to Firebase
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only functions --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}