name: CI - Functions

on:
  push:
    branches:
      - master
    paths:
      - app/functions/**

jobs:
  build:
    name: Deploy functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: yarn add firebase-tools
      - name: Set functions secrets
        working-directory: ./app
        run: ./node_modules/.bin/firebase functions:config:set due_dill_api.key=${DUE_DILL_API_KEY} trulioo_api.key=${TRULIOO_API_KEY} firebase_service_account_private_key_id.key=${FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID} firebase_service_account_client_email_id.key=${FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL_ID} firebase_service_account_client_email.key=${FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL} firebase_service_account_private_key.key=${FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY} companies_house_api.key=${COMPANIES_HOUSE_API_KEY} companies_house_api.id="Companies house" --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY}}
          DUE_DILL_API_KEY: ${{ secrets.DUE_DILL_API_KEY}}
          TRULIOO_API_KEY: ${{ secrets.TRULIOO_API_KEY}}
          FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY_ID}}
          FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIVATE_KEY}}
          FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_EMAIL}}
          FIREBASE_SERVICE_ACCOUNT_CLIENT_ID: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLIENT_ID}}
      - name: Install function dependencies
        working-directory: ./app/functions
        run: npm install 
      - name: Deploy functions to Firebase
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only functions --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}