name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: yarn
      - name: Build
        working-directory: ./app
        run: yarn run build
      - name: Deploy hosting to Firebase
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only hosting  
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Set functions secrets
        working-directory: ./app
        run: ./node_modules/.bin/firebase functions:config:set companies_house_api_key=${COMPANIES_HOUSE_API_KEY} --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          COMPANIES_HOUSE_API_KEY: ${{ secrets.COMPANIES_HOUSE_API_KEY}}
      - name: Install function dependencies
        working-directory: ./app/functions
        run: npm install 
      - name: Deploy functions to Firebase
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only functions --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}