name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: npm install
      - name: Build
        working-directory: ./app
        run: npm run build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Firebase CLI
        working-directory: ./app
        run: npm install firebase-cli
      - name: Deploy to Firebase
        # uses: w9jds/firebase-action@master
        working-directory: ./app
        run: firebase deploy --token FIREBASE_TOKEN --only hosting --non-interactive
        # with:
        #   args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
