name: CI - React App Staging

on:
  push:
    branches:
      - develop
    paths:
      - app/**
      - '!app/functions/**'
jobs:
  # cypress:
  #   name: cypress
  #   runs-on: ubuntu-16.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: start app
  #       run: cd ./app && yarn test:e2e
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v1
  #       # working-directory: ./app
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: yarn
      - name: Unit tests
        working-directory: ./app
        run: yarn test
        env:
          CI: true
      - name: Serve App and e2e
        working-directory: ./app
        # run: yarn start-ci
        # env:
        #   CI: false
        run: ./node_modules/.bin/firebase serve --only hosting -P staging --token $FIREBASE_TOKEN & yarn cypress run
        env:
          FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
      - name: Build
        working-directory: ./app
        run: yarn run build
        env:
          CI: false
      # - name: Checkout
      #   uses: actions/checkout@v1
      - name: Deploy hosting to Firebase (staging)
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only hosting -P staging --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
          