name: CI - React App Staging

on:
  push:
    branches:
      - develop
    paths:
      - app/**
      - '!app/functions/**'
jobs:
  cypress:
    name: cypress
    runs-on: ubuntu-16.04
    steps:
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        working-directory: ./app
        with:
          browser: chrome
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: yarn
      - name: Unit tests
        working-directory: ./app
        run: yarn test
        env:
          CI: true
      - name: Build
        working-directory: ./app
        run: yarn run build
        env:
          CI: false
      - name: Deploy hosting to Firebase (staging)
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only hosting -P staging --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
          