name: CI - React App Production

on:
  push:
    branches:
      - master
    paths:
      - app/**
      - '!app/functions/**'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./app
        run: yarn
      - name: Unit tests
        working-directory: ./app
        run: yarn test
        env:
          CI: true
      - name: Build
        working-directory: ./app
        run: yarn run build
      - name: Deploy hosting to Firebase (production)
        working-directory: ./app
        run: ./node_modules/.bin/firebase deploy --only hosting -P production 
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          